In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print([1, 2, 3, 4, 5])

[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
a = np.zeros(10)
print(a)

b = np.eye(3)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
c = np.arange(1, 21, 3)  # 3번째 인자는 갭
print(c)

[ 1  4  7 10 13 16 19]


In [10]:
# 데이터 분석 -> 통계 -> 그래프 -> 구간
d = np.linspace(0, 10, 5)
print(d)

[ 0.   2.5  5.   7.5 10. ]


In [178]:
e = np.random.random()
print(e)

e = np.random.randint(1, 10, [3, 3])
print(e)

e = np.random.randn(10)
print(e)

0.19737235263506558
[[5 5 1]
 [7 4 1]
 [3 8 1]]
[-1.27223474 -0.04883755  0.73041212 -0.83674566 -0.91283256 -0.88700197
 -0.35689723 -0.10975633 -0.70801024  2.22188796]


In [185]:
f = np.arange(11)
print(f[f % 2 == 0])
five_up = f >= 5
print(five_up)

g = f[(f > 5) & (f < 11)]
print(g)
g = f[(f > 9) | (f < 5)]
print(g)
g = f[~(f % 3 == 0)]
print(g)

[ 0  2  4  6  8 10]
[False False False False False  True  True  True  True  True  True]
[ 6  7  8  9 10]
[ 0  1  2  3  4 10]
[ 1  2  4  5  7  8 10]


In [194]:
h = np.arange(1, 10).reshape(3, 3)
# print(h.sum())
# print(np.sum(h))
print(h.sum(axis=0))  # [0] ~ [2] 행의 값을 더하기
print(h.sum(axis=1))  # [0] ~ [2] 열의 값을 더하기

[12 15 18]
[ 6 15 24]


In [195]:
# 브로드캐스팅 연산 사용 X
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 1, 1, 1, 1])
print(x + y)
# 브로드캐스팅 연산 사용 O
y = 1
print(x + y)

[2 3 4 5 6]
[2 3 4 5 6]


In [198]:
a = np.arange(1, 25).reshape(4, 6)
print(a)
print(a + 100)  # 스칼라 배열(암시적)

new_arr = np.full_like(a, 100)  # a와 같은 모양 + 100으로 구성
print(a + new_arr)  # 스칼라 배열(명시적)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]
[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]


In [200]:
a = np.arange(5).reshape(1, 5)
b = np.arange(5).reshape(5, 1)
print(a)
print(b)
print(a + b)

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
