In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
# 1. 다음은 1부터 10까지 1차원 배열을 생성하고 배열의 속성을 알아보는 프로그램이다.
# 실행결과를 확인하고 빈칸에 가장 알맞은 속성을 작성하세요.
import numpy as np
arr = np.arange(1,11)
print(arr)
print('ndum: ', arr.ndim)
print(arr.shape)
print(arr.dtype)
print('size: ', arr.size)

[ 1  2  3  4  5  6  7  8  9 10]
ndum:  1
(10,)
int64
size:  10


In [21]:
# 2. 다음 각각의 문제들을 넘파이를 활용하여 해결해 보세요.

## 길이 10~50인 벡터를 만들고 벡터를 반전시켜 출력해 보세요.
arr = np.arange(10, 50)
print(f"2-1: {arr[::-1]}")

## 랜덤 값이 있는 10 x 10 배열을 만들고 최댓값과 최소값을 찾아보세요.
arr2 = np.random.random(size=(10, 10))
print(f"2-2: {np.max(arr2), np.min(arr2)}")

## 0~8 범위의 값을 사용하여 3x3 배열을 생성해 보세요.
arr3 = np.arange(9).reshape(3, 3)
print(f"2-3: {arr3}")

## 다음과 같이 1에서 24까지의 값을 가지는 4x6 크기의 2차원 행렬 arr을 생성해 보세요.
arr4 = np.arange(1, 25).reshape(4, 6)
print(f"2-4: {arr4}")

## arr배열에 슬라이싱을 적용하여 다음과 같은 값을 가지는 배열을 생성해 보세요.
print(f"2-5: {arr4[1:3, 1:5]}")

## arr배열에 슬라이싱을 적용하여 다음과 같은 값을 가지는 배열을 생성해 보세요.
print(f"2-6: {arr4[2:, ::-1]}")

## arr배열에서 2의 배수만 출력해 보세요.
print(f"2-7: {arr4[(arr4 % 2 == 0)]}")

## arr배열에서 10부터 20까지의 값만 출력해 보세요.
print(f"2-8: {arr4[(arr4 >= 10) & (arr4 <= 20)]}")

2-1: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
2-2: (np.float64(0.9949300521723343), np.float64(0.003122573778305604))
2-3: [[0 1 2]
 [3 4 5]
 [6 7 8]]
2-4: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
2-5: [[ 8  9 10 11]
 [14 15 16 17]]
2-6: [[18 17 16 15 14 13]
 [24 23 22 21 20 19]]
2-7: [ 2  4  6  8 10 12 14 16 18 20 22 24]
2-8: [10 11 12 13 14 15 16 17 18 19 20]


In [9]:
# 3. numpy 배열을 사용하여 1부터 20까지의 연속된 정수값을 가지는 1차원 배열을 생성하여
# 실행 결과와 같이 출력되기 위해서 밑줄에 들어갈 알맞은 코드를 쓰세요.
arr = np.arange(1, 21)
print('마지막 원소: ')
print('모든 원소의 합: ')
print('모든 원소의 평균: ')

1월은 겨울


In [11]:
# 4. 두 번의 점수를 입력받아 합격 및 불합격 여부를 출력하는 프로그램을 작성하세요.

score1 = float(input("1차 점수 입력: "))
score2 = float(input("2차 점수 입력: "))

if ((score1 + score2 / 2.0) >= 70) and (score1 >= 50) and (score2 >= 50):
    print("합격")
else:
    print("불합격")

불합격


In [22]:
# 5. 컴퓨터가 생각한 1 ~ 30 사이의 숫자를 맞히는 게임 프로그램을 작성하세요.
import random

cpuNum = random.randint(1, 30)
while True:
    print("<< 1~30 숫자 맞히기 게임 >>")
    userNum = int(input("숫자 입력(종료 0): "))

    if userNum == 0:
        break

    if cpuNum == userNum:
        print("정답!!")
        break
    elif cpuNum > userNum:
        print("더 큰 숫자 입력!")
    elif cpuNum < userNum:
        print("더 작은 숫자 입력!")
    else:
        print("오류: 1~30 사이의 숫자만 입력하세요!")

print("게임 종료")

<< 1~30 숫자 맞히기 게임 >>
더 작은 숫자 입력!
<< 1~30 숫자 맞히기 게임 >>
더 작은 숫자 입력!
<< 1~30 숫자 맞히기 게임 >>
정답!!
게임 종료


In [12]:
# 6. 행운의 로또 복권 번호를 생성하여 리스트에 저장한 후 출력하세요.

import random

lottoNum = []
print("<< 생성된 로또 번호 >>")
while len(lottoNum) < 6:
    num = random.randint(1, 45)
    lottoNum.append(num)

print(lottoNum)

<< 생성된 로또 번호 >>
[28, 8, 21, 22, 17, 16]


In [3]:
# 7. 타자 연습 게임 프로그램을 작성하세요.
import random

typingList = [
    "낙하",
    "불구덩이든",
    "워커홀릭",
    "사계",
    "그대라는 시",
    "비의 랩소디",
]
typingStr = random.choice(typingList)
count = 1
print("타자게임 시작 (엔터 입력)")
while True:
    print(f"문제 {count} (종료 0): {typingStr}")
    userTyping = input()
    if userTyping == "0":
        print("게임 종료")
        break
    if typingStr == userTyping:
        print("맞음!!")
        typingStr = random.choice(typingList)
    else:
        print("틀림!! 다시!")
    count += 1

타자게임 시작 (엔터 입력)
문제 1 (종료 0): 그대라는 시
맞음!!
문제 2 (종료 0): 비의 랩소디
틀림!! 다시!
문제 3 (종료 0): 비의 랩소디
맞음!!
문제 4 (종료 0): 워커홀릭
틀림!! 다시!
문제 5 (종료 0): 워커홀릭
맞음!!
문제 6 (종료 0): 불구덩이든
게임 종료


In [21]:
# 8. MT 장소를 선정하기 위한 프로그램이다. 실행결과와 같이 MT 장소를 입력받아 딕셔너리에 저장한 후 투표 결과와 최다득표 MT 장소를 화면에 출력하세요.
mtList = {
    "대성리": 0,
    "춘천": 0,
    "을왕리": 0,
    "청평": 0,
}

for i in range(4):
    mt = input()
    if mt in mtList:
        mtList[mt] += 1
    else:
        print(f"{mt}는 올바른 장소가 아닙니다.")

print("<< MT 장소 투표 >>")
for mt in mtList:
    print(f"장소 : {mt}")

for mt, value in mtList.items():
    print(f"{mt}:{value}표")

maxValue = max(mtList.values())
maxMt = [mt for mt, value in mtList.items() if value == maxValue]
print(f"최다득표: {maxMt[0]} {maxValue}표")

<< MT 장소 투표 >>
장소 : 대성리
장소 : 춘천
장소 : 을왕리
장소 : 청평
대성리:0표
춘천:3표
을왕리:1표
청평:0표
최다득표: 춘천 3표


In [ ]:
# 9. 다음 파이썬 코드의 결과를 예측하세요.
def print_lyrics():
    print("Twinkle, twinkle, little star,")
    print("How I wonder what you are!")
    print("Up above the world so high,")
    print("Like a diamond in the sky.")
    print("Twinkle, twinkle, little star,")
    print("How I wonder what you are!")


print("Hoo", "ooh" * 4)
print()
print_lyrics()

Hoo oohoohoohooh

Twinkle, twinkle, little star,
How I wonder what you are!
Up above the world so high,
Like a diamond in the sky.
Twinkle, twinkle, little star,
How I wonder what you are!


In [2]:
# 10. 사이렌오더를 통해 음료를 미리 예약하는 프로그램을 작성하세요.
def price(menue: int):

    if menue == 1:
        return print("아메리카노: 3,000원")
    elif menue == 2:
        return print("카페라떼 : 4,000원")
    elif menue == 3:
        return print("바닐라라떼 : 4,500원")
    else:
        print("잘못된 숫자를 입력했습니다.")


menue = int(input("메뉴선택(1:아메리카노/2:카페라떼/3:바닐라라떼) "))
price(menue)

아메리카노: 3,000원


In [15]:
# 11. 다음 빈 곳에 알맞은 파이썬 코드를 작성하세요.
## 확장자가 .jpg, .png인 이미지 파일만 출력되도록 람다 표현식을 사용한다.

files = ["report.hwp", "newJeans", "attention.png", "ditto.jpg", "address.xslx"]
print(list(filter(lambda file: file.endswith((".png", ".jpg")), files)))

['attention.png', 'ditto.jpg']


In [32]:
# 12. 파일(weather.txt)에는 다음과 같은 형태로 하반기 기온에 대한 월별 최저기온과 최고기온이 저장되어 있다.
# 파일 내용을 읽어서 월의 평균기온(최저기온과 최고기온)을 계산한 후에 실행 화면과 같이 출력하세요.
f = open("weather.txt")
dataList = f.readlines()
for data in dataList:
    result = data.strip("\n").split(",")
    avg = round((float(result[1]) + float(result[2])) / 2.0, 1)
    print(f"{result[0]}월 평균기온은 {avg}℃입니다.")
f.close()

7월 평균기온은 23.0℃입니다.
8월 평균기온은 28.2℃입니다.
9월 평균기온은 21.9℃입니다.
10월 평균기온은 16.6℃입니다.
11월 평균기온은 11.0℃입니다.
12월 평균기온은 3.1℃입니다.


In [83]:
# 13. 임의의 엑셀 파일을 이용하여 다음 작업을 수행해 보세요.
# - xlsx 파일을 읽어 데이터프레임으로 저장하여 확인한다.
# - 데이터프레임 데이터를 생성하여 기존 데이터프레임에 추가한다.
# - 하나로 합쳐진 데이터프레임 데이터를 xlsx 파일에 저장한다.
import pandas as pd

myFile = pd.read_excel("../resources/3장/my_addr.xlsx")
newDf = pd.DataFrame(
    [["정한서", "010-9928-2667", "jhs@naver.com"]], columns=myFile.columns
)
resultDf = pd.concat([myFile, newDf], ignore_index=True)
resultDf.to_excel("../resources/3장/my_addr.xlsx", index=False)
resultDf

이름            연락처            이메일
0  이순신  010-1234-1234   lee@test.com
1  강감찬  010-1111-1111  kang@test.com
2  홍길동  010-2222-2222  hong@test.com
3  정한서  010-9928-2667  jhs@naver.com